title: 'Azure Table Extractor'
description: 'Extract tables from your documents using Azure Document Intelligence.'
instructions: ''
type: object
documents:
  - selected
properties:
  start_page:
    title: Starting page number
    type: integer
    description: 'Page number where the table(s) begin'
    default: 1
  end_page:
    title: Ending page number
    type: integer
    description: 'Page number where table(s) end'
    default: 1
  output_format:
    title: Output format
    type: string
    default: json
    enum:
      - csv
      - json
categories: 
  - extraction
  - premium
cost:
  price: 7
  amount: 1
  unit: page
version: 2
